# Site
title: Zeus
subtitle: ''
description: ''
keywords:
author: Zeus
 
timezone: ''

theme: fluid  # 指定主题

language: zh-CN  # 指定语言，会影响主题显示的语言，按需修改
navbar:
  blog_title: "Zeus"
 
  
 

# deploy:
#   type: git
#   repo: https://github.com/nicolastinkl/nicolastinkl.github.io.git  
#   branch: [branch]
#   token: [token]
